#!/usr/bin/expect

set path [lindex $argv 0]
set password [lindex $argv 1]
set txPasswdConfirmations [lindex $argv 2]
set txPasswdPhrase [lindex $argv 3]

spawn ./delegate.sh $path

for {set i 1} {$i<=$txPasswdConfirmations} {incr i} {
    expect "$txPasswdPhrase" { send "$password\r"; }
    sleep 1
}

sleep 15

for {set i 1} {$i<=$txPasswdConfirmations} {incr i} {
    expect "$txPasswdPhrase" { send "$password\r"; }
    sleep 1
}

interact
